name: Build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.x'

      - name: Install NPM Dependencies
        run: npm install

      - name: Import signing certificate
        if: matrix.os == 'macos-latest'
        env:
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
        run: |
          echo "$APPLE_CERTIFICATE" | base64 --decode > apple.p12
          security create-keychain -p temporary build.keychain
          security set-keychain-settings build.keychain
          security unlock-keychain -p temporary build.keychain
          security import apple.p12 -k build.keychain -P "$APPLE_CERTIFICATE_PASSWORD" -A
          security set-key-partition-list -S apple-tool:,apple: -s -k temporary build.keychain
          security list-keychains -d user -s build.keychain

      - name: Install Snapcraft
        if: matrix.os == 'ubuntu-latest'
        run: |
            sudo snap install snapcraft --classic

      - name: Build & Publish Mac
        if: matrix.os == 'macos-latest'
        run: npm run publish-mac
        env:
          VITE_LSP_WEBSOCKET_PORT: 54331
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

      - name: Clean up Mac keychain
        if: matrix.os == 'macos-latest'
        run: |
          security delete-keychain build.keychain

      - name: Build & Publish Linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run publish-linux
        env:
          VITE_LSP_WEBSOCKET_PORT: 54331
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
